DreamBoard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wishlist.urls')),

    path('users/', include('users.urls', namespace="users"))
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import LoginUser
from django.contrib.auth.views import LogoutView
from DreamBoard import settings
from users.views import Register

app_name = "users"

urlpatterns = [


    path('', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('login/', LoginUser.as_view(), name='login'),

]
#path('registration/', SignUpView.as_view(), name='registrations'),
#path('login/', LoginUser.as_view(), name='login'),
#path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

wishlist/urls.py
from django.urls import path, reverse_lazy, include
from django.views.generic import TemplateView

from . import views
from .views import *

urlpatterns = [
    path('a', views.index),
    path('', TemplateView.as_view(template_name='MainPage.html'), name='home'),
    path('users/', include('users.urls', namespace="users")),
    path('createlist', CreateList.as_view(), name='create'),
    path('list', ViewList.as_view(), name='list')
]

wishlist/models.py
from django.db import models
from django.urls import reverse
#from DreamBoard.DreamBoard import settings
# Create your models here.
from DreamBoard import settings


class Status(models.Model):
    """выносная модель статуса пользователя"""
    status = models.CharField(max_length=100, verbose_name="статус")

    def __str__(self):
        return ""

    def get_absolute_url(self):
        return reverse("Status")

    class Meta:
        verbose_name = "статус"
        verbose_name_plural = "статусы"


class CountPeople(models.Model):
    """модель настройки колво людей для прем акка"""
    count_people = models.IntegerField(verbose_name='кол-во людей')

    def __str__(self):
        return "porebyx"

    class Meta:
        verbose_name = "настройка кол-ва людей"
        verbose_name_plural = "настройки кол-ва людей"


class Giver(models.Model):
    """модель дарителя"""
    list_wish_id = models.ForeignKey("WishList", on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return "popa"

    class Meta:
        verbose_name = "даритель"
        verbose_name_plural = "дарители"


class Booking(models.Model):
    """модель бронирования"""
    goods_list_wish_id = models.ForeignKey("GoodsInWishList", on_delete=models.CASCADE)
    giver_id = models.ForeignKey(Giver, on_delete=models.CASCADE)

    def __str__(self):
        return "jepa"

    class Meta:
        verbose_name = "бронь"
        verbose_name_plural = "бронирование"


class GoodsInWishList(models.Model):
    """ модель товары в списке желаний"""
    list_wish_id = models.ForeignKey("WishList", on_delete=models.CASCADE)
    goods_id = models.ForeignKey("Goods", on_delete=models.CASCADE)

    def __str__(self):
        return "aaaaa ya ystal"

    class Meta:
        verbose_name = "помолчу"
        verbose_name_plural = "помолчим"


class Goods(models.Model):
    """модель товаров"""
    title = models.CharField(max_length=250, verbose_name='Название')
    link = models.TextField()

    def __str__(self):
        return "tovar"

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"


class WishList(models.Model):
    """модель вишлиста"""
    title = models.CharField(max_length=250, verbose_name='Название')
    #count_user = models.IntegerField(verbose_name='кол-во людей в списке пользователей')
    owner_user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

wishlist/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import WishList, Goods


class AddWishList(forms.ModelForm):
    class Meta:
        model = WishList
        fields = ["title"]


class AddGoods(forms.ModelForm):
    class Meta:
        model = Goods
        fields = ["title", "link"]


class CreateWishList(forms.Form):
    title = forms.CharField(max_length=255)
    goods_name = forms.CharField(max_length=255)
    link = forms.CharField(max_length=255)

wishlist/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView, TemplateView, ListView

from wishlist.forms import AddWishList, AddGoods, CreateWishList
from wishlist.models import WishList


def index(requerst):
    #return HttpResponse("wishlist")
    return render(requerst, 'MainPage.html')


def login(requerst):
    return render(requerst, 'login.html')


class CreateList(CreateView):
    #model = WishList
    form_class = AddWishList
    template_name = 'create_list.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super(CreateList, self).get_context_data(**kwargs)
        context['wishlist'] = AddWishList
        context['goods'] = AddGoods
        return context

    def form_valid(self, form):
        article = form.save(commit=False)
        article.owner_user_id = self.request.user
        #article.save()  # This is redundant, see comments.
        return super(CreateList, self).form_valid(form)


class ViewList(ListView):
    model = WishList
    template_name = 'list.html'

wishlist/templates/MainPage.html
<!DOCTYPE html>
<html lang="en">
<head>

	<link rel="stylesheet" href="/static/css/main.css">



	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Главная</title>

	<script src="https://kit.fontawesome.com/bfec730d56.js" crossorigin="anonymous"></script>
	<script src="static/libs/gsap/gsap.min.js" defer></script>
	<script src="static/libs/gsap/ScrollTrigger.min.js" defer></script>
	<script src="static/libs/gsap/ScrollSmoother.min.js" defer></script>

	<script src="static/js/app.js" defer></script>

</head>
	<script src="https://kit.fontawesome.com/bfec730d56.js" crossorigin="anonymous"></script>
<body>

	<div class="wrapper">
		<div class="content">


			<section class="menu">
				<a href="#" class="logo">
					<img src="static/img/logo.svg" alt="DreamBoard">
				</a>
				<nav class="navbar">

					<a href="#">ГЛАВНАЯ</a>

					<a href="{% url 'create' %}">СОЗДАТЬ</a>
					<a href="#">О НАС</a>

					{% if user.is_authenticated %}
					<a href="{% url 'users:logout' %}">ВЫЙТИ</a>
					<a href="{% url 'list' %}">СПИСКИ</a>
					{% else %}
					<a href="{% url 'users:login' %}">ВХОД</a>
					<a href="{% url 'users:register' %}">РЕГИСТРАЦИЯ</a>
					{% endif %}

				</nav>

				<div id="menucompact"><i class="fas fa-bars" onclick="changeIcon(this)"></i></div>


			</section>

			<script>
				let navbar = document.querySelector('.menu .navbar');
				let menu = document.querySelector('#menu');

				menu.onclick = () => {
					navbar.classList.toggle('active');
				}

				let changeIcon = function(icon) {
					icon.classList.toggle('fa-times');
				}
			</script>

			<header class="main-header">
				<div class="layers">
					<div class="layer__header">
						<div class="layers__caption">Welcome to</div>
						<div class="layers__title">DreamBoard</div>
					</div>
					<div class="layer layers__base" style="background-image: url(static/img/layer-base.png);"></div>
					<div class="layer layers__middle" style="background-image: url(static/img/layer-middle.png);"></div>
					<div class="layer layers__front" style="background-image: url(static/img/layer-front.png);"></div>
				</div>
			</header>

			<article class="main-article" style="background-image: url(static/img/dungeon.jpg);">
				<div class="main-article__content">
					<h2 class="main-article__header">Время помечтать!</h2>
					<p class="main-article__paragraph">Создайте свой список желаний, чтобы получить то, чего вы хотите на самом деле</p>
				</div>
				<div class="copy">©DREAMBOARD</div>
			</article>

		</div>
	</div>

</body>
</html>

wishlist/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User autenticate</title>
</head>
<body>
<ul>
    <li>
        User {{ user }}
    </li>
    <li>
        <a href="{% url 'home' %}">Home</a>
    </li>

</ul>
{% block content %}
{% endblock %}

</body>
</html>

wishlist/templates/create_list.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in wishlist %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    {% for f in goods %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Отправить</button></p>
</form>

{% endblock %}

wishlist/templates/dsjdfkjsdfjsd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

wishlist/templates/list.html
{% extends 'base.html' %}

{% block content %}
{% for p in object_list %}
    {{ p.title }}
{% endfor %}

{% endblock %}

wishlist/templates/tdy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>